src/Presentation/Nop.Web/Administration/Models/Payments/PaymentMethodModel.cs
using System.Web.Mvc;
using System.Web.Routing;
using Nop.Web.Framework;
using Nop.Web.Framework.Mvc;

namespace Nop.Admin.Models.Payments
{
    public partial class PaymentMethodModel : BaseNopModel
    {
        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.FriendlyName")]
        [AllowHtml]
        public string FriendlyName { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SystemName")]
        [AllowHtml]
        public string SystemName { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.IsActive")]
        public bool IsActive { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.Logo")]
        public string LogoUrl { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportCapture")]
        public bool SupportCapture { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportPartiallyRefund")]
        public bool SupportPartiallyRefund { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportRefund")]
        public bool SupportRefund { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportVoid")]
        public bool SupportVoid { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.RecurringPaymentType")]
        public string RecurringPaymentType { get; set; }
        



        public string ConfigurationActionName { get; set; }
        public string ConfigurationControllerName { get; set; }
        public RouteValueDictionary ConfigurationRouteValues { get; set; }
    }
}

src/Presentation/Nop.Web/Administration/Models/Payments/PaymentMethodRestrictionModel.cs
using System.Collections.Generic;
using Nop.Admin.Models.Directory;
using Nop.Web.Framework.Mvc;

namespace Nop.Admin.Models.Payments
{
    public partial class PaymentMethodRestrictionModel : BaseNopModel
    {
        public PaymentMethodRestrictionModel()
        {
            AvailablePaymentMethods = new List<PaymentMethodModel>();
            AvailableCountries = new List<CountryModel>();
            Resticted = new Dictionary<string, IDictionary<int, bool>>();
        }
        public IList<PaymentMethodModel> AvailablePaymentMethods { get; set; }
        public IList<CountryModel> AvailableCountries { get; set; }

        //[payment method system name] / [customer role id] / [resticted]
        public IDictionary<string, IDictionary<int, bool>> Resticted { get; set; }
    }
}

src/Presentation/Nop.Web/Administration/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using Nop.Admin.Extensions;
using Nop.Admin.Models.Payments;
using Nop.Core;
using Nop.Core.Domain.Payments;
using Nop.Core.Plugins;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Payments;
using Nop.Services.Security;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;

namespace Nop.Admin.Controllers
{
    public partial class PaymentController : BaseAdminController
	{
		#region Fields

        private readonly IPaymentService _paymentService;
        private readonly PaymentSettings _paymentSettings;
        private readonly ISettingService _settingService;
        private readonly IPermissionService _permissionService;
	    private readonly ICountryService _countryService;
        private readonly IPluginFinder _pluginFinder;
	    private readonly IWebHelper _webHelper;
	    private readonly ILocalizationService _localizationService;

		#endregion

		#region Constructors

        public PaymentController(IPaymentService paymentService,
            PaymentSettings paymentSettings,
            ISettingService settingService, 
            IPermissionService permissionService,
            ICountryService countryService,
            IPluginFinder pluginFinder,
            IWebHelper webHelper,
            ILocalizationService localizationService)
		{
            this._paymentService = paymentService;
            this._paymentSettings = paymentSettings;
            this._settingService = settingService;
            this._permissionService = permissionService;
            this._countryService = countryService;
            this._pluginFinder = pluginFinder;
            this._webHelper = webHelper;
            this._localizationService = localizationService;
		}

		#endregion 

        #region Methods

        public ActionResult Methods()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            return View();
        }

        [HttpPost]
        public ActionResult Methods(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            var paymentMethodsModel = new List<PaymentMethodModel>();
            var paymentMethods = _paymentService.LoadAllPaymentMethods();
            foreach (var paymentMethod in paymentMethods)
            {
                var tmp1 = paymentMethod.ToModel();
                tmp1.IsActive = paymentMethod.IsPaymentMethodActive(_paymentSettings);
                tmp1.LogoUrl = paymentMethod.PluginDescriptor.GetLogoUrl(_webHelper);
                paymentMethodsModel.Add(tmp1);
            }
            paymentMethodsModel = paymentMethodsModel.ToList();
            var gridModel = new DataSourceResult
            {
                Data = paymentMethodsModel,
                Total = paymentMethodsModel.Count
            };

            return Json(gridModel);
        }

        [HttpPost]
        public ActionResult MethodUpdate([Bind(Exclude = "ConfigurationRouteValues")] PaymentMethodModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            var pm = _paymentService.LoadPaymentMethodBySystemName(model.SystemName);
            if (pm.IsPaymentMethodActive(_paymentSettings))
            {
                if (!model.IsActive)
                {
                    //mark as disabled
                    _paymentSettings.ActivePaymentMethodSystemNames.Remove(pm.PluginDescriptor.SystemName);
                    _settingService.SaveSetting(_paymentSettings);
                }
            }
            else
            {
                if (model.IsActive)
                {
                    //mark as active
                    _paymentSettings.ActivePaymentMethodSystemNames.Add(pm.PluginDescriptor.SystemName);
                    _settingService.SaveSetting(_paymentSettings);
                }
            }
            var pluginDescriptor = pm.PluginDescriptor;
            pluginDescriptor.FriendlyName = model.FriendlyName;
            pluginDescriptor.DisplayOrder = model.DisplayOrder;
            PluginFileParser.SavePluginDescriptionFile(pluginDescriptor);
            //reset plugin cache
            _pluginFinder.ReloadPlugins();

            return new NullJsonResult();
        }

        public ActionResult ConfigureMethod(string systemName)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            var pm = _paymentService.LoadPaymentMethodBySystemName(systemName);
            if (pm == null)
                //No payment method found with the specified id
                return RedirectToAction("Methods");

            var model = pm.ToModel();
            string actionName, controllerName;
            RouteValueDictionary routeValues;
            pm.GetConfigurationRoute(out actionName, out controllerName, out routeValues);
            model.ConfigurationActionName = actionName;
            model.ConfigurationControllerName = controllerName;
            model.ConfigurationRouteValues = routeValues;
            return View(model);
        }

        public ActionResult MethodRestrictions()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            var model = new PaymentMethodRestrictionModel();

            var paymentMethods = _paymentService.LoadAllPaymentMethods();
            var countries = _countryService.GetAllCountries(true);
            foreach (var pm in paymentMethods)
            {
                model.AvailablePaymentMethods.Add(pm.ToModel());
            }
            foreach (var c in countries)
            {
                model.AvailableCountries.Add(c.ToModel());
            }
            foreach (var pm in paymentMethods)
            {
                var restictedCountries = _paymentService.GetRestictedCountryIds(pm);
                foreach (var c in countries)
                {
                    bool resticted = restictedCountries.Contains(c.Id);
                    if (!model.Resticted.ContainsKey(pm.PluginDescriptor.SystemName))
                        model.Resticted[pm.PluginDescriptor.SystemName] = new Dictionary<int, bool>();
                    model.Resticted[pm.PluginDescriptor.SystemName][c.Id] = resticted;
                }
            }

            return View(model);
        }

        [HttpPost, ActionName("MethodRestrictions")]
        public ActionResult MethodRestrictionsSave(FormCollection form)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            var paymentMethods = _paymentService.LoadAllPaymentMethods();
            var countries = _countryService.GetAllCountries(true);

            foreach (var pm in paymentMethods)
            {
                string formKey = "restrict_" + pm.PluginDescriptor.SystemName;
                var countryIdsToRestrict = (form[formKey] != null ? form[formKey].Split(new [] { ',' }, StringSplitOptions.RemoveEmptyEntries).ToList() : new List<string>())
                    .Select(x => Convert.ToInt32(x)).ToList();

                var newCountryIds = new List<int>();
                foreach (var c in countries)
                {
                    if (countryIdsToRestrict.Contains(c.Id))
                    {
                        newCountryIds.Add(c.Id);
                    }
                }
                _paymentService.SaveRestictedCountryIds(pm, newCountryIds);
            }

            SuccessNotification(_localizationService.GetResource("Admin.Configuration.Payment.MethodRestrictions.Updated"));
            return RedirectToAction("MethodRestrictions");
        }

        #endregion
    }
}

src/Presentation/Nop.Web/Administration/Views/Payment/ConfigureMethod.cshtml
@model PaymentMethodModel
@{    
    //page title
    ViewBag.Title = T("Admin.Configuration.Payment.Methods.Configure").Text + " - " + Model.FriendlyName;
}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-configuration.png")" alt="" />
        @T("Admin.Configuration.Payment.Methods.Configure") - @Model.FriendlyName @Html.ActionLink("(" + T("Admin.Configuration.Payment.Methods.BackToList") + ")", "Methods")
    </div>
</div>
@if (!String.IsNullOrEmpty(Model.ConfigurationActionName))
{
    @Html.Action(Model.ConfigurationActionName, Model.ConfigurationControllerName, Model.ConfigurationRouteValues);
}
else
{
    @T("Admin.Common.ConfigurationNotRequired")
}

src/Presentation/Nop.Web/Administration/Views/Payment/MethodRestrictions.cshtml
@model PaymentMethodRestrictionModel
@{               
    //page title
    ViewBag.Title = T("Admin.Configuration.Payment.MethodRestrictions").Text;
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="section-header">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-configuration.png")" alt="" />
            @T("Admin.Configuration.Payment.MethodRestrictions")
        </div>
        <div class="options">
            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
        </div>
    </div>
    
    <table class="adminContent">
        <tr>
            <td>
                @T("Admin.Configuration.Payment.MethodRestrictions.Description")
                <br />
                <br />
                @if (Model.AvailablePaymentMethods.Count == 0)
                {
                    <text>No payment methods installed</text>
                }
                else if (Model.AvailableCountries.Count == 0)
                {
                    <text>No countries available</text>
                }
                else
                {  
                    <script type="text/javascript">
                        $(document).ready(function () {            
                            @foreach (var pm in Model.AvailablePaymentMethods)
                            {
                                var systemNameWithoutDot = pm.SystemName.Replace(".", "");
                                <text>
                                $('#selectall-@(systemNameWithoutDot)').click(function () {
                                        $('.restrict_@(systemNameWithoutDot)').attr('checked', $(this).is(':checked')).change();
                                    });

                                </text>
                            }
                        });
                    </script>
                    <table class="tablestyle" cellspacing="0" rules="all" border="1" style="width: 100%;
                                      border-collapse: collapse;">
                        <tbody>
                            <tr class="headerstyle">
                                <th scope="col">
                                    <strong>@T("Admin.Configuration.Payment.MethodRestrictions.Country")</strong>
                                </th>
                                @foreach (var pm in Model.AvailablePaymentMethods)
                                {
                                    var systemNameWithoutDot = pm.SystemName.Replace(".", "");
                                    <th scope="col">
                                        <strong>@pm.FriendlyName</strong>
                                        <input type="checkbox" id="selectall-@(systemNameWithoutDot)" />
                                    </th>
                                }
                            </tr>
                            @{
                                bool altRow = true;
                            }
                            @foreach (var c in Model.AvailableCountries)
                            {
                                altRow = !altRow;
                                <tr class="@(altRow ? "altrowstyle" : "rowstyle")">
                                    <td>
                                        <span>@c.Name</span>
                                    </td>
                                    @foreach (var pm in Model.AvailablePaymentMethods)
                                    {
                                        var resticted = Model.Resticted.ContainsKey(pm.SystemName) && Model.Resticted[pm.SystemName][c.Id];

                                        var systemNameWithoutDot = pm.SystemName.Replace(".", "");
                                        <td>
                                            <input class="restrict_@(systemNameWithoutDot)" type="checkbox" value="@(c.Id)" name="restrict_@(pm.SystemName)" @(resticted ? " checked=checked" : null) />
                                        </td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </td>
        </tr>
    </table>

}

src/Presentation/Nop.Web/Administration/Views/Payment/Methods.cshtml
@{    
    //page title
    ViewBag.Title = T("Admin.Configuration.Payment.Methods").Text;
}
@Html.AntiForgeryToken()
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-configuration.png")" alt="" />
        @T("Admin.Configuration.Payment.Methods")
    </div>
</div>
<table class="adminContent">
    <tr>
        <td>
            <div id="paymentmethods-grid"></div>

            <script>
                $(document).ready(function () {
                    $("#paymentmethods-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("Methods", "Payment"))",
                                    type: "POST",
                                    dataType: "json",
                                    data: addAntiForgeryToken
                                },
                                update: {
                                    url: "@Html.Raw(Url.Action("MethodUpdate", "Payment"))",
                                    type: "POST",
                                    dataType: "json",
                                    data: addAntiForgeryToken
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors",
                                model: {
                                    id: "SystemName",
                                    fields: {
                                        FriendlyName: { editable: true, type: "string" },
                                        SystemName: { editable: false, type: "string" },
                                        LogoUrl: { editable: false, type: "string" },
                                        SupportCapture: { editable: false, type: "boolean" },
                                        SupportRefund: { editable: false, type: "boolean" },
                                        SupportPartiallyRefund: { editable: false, type: "boolean" },
                                        SupportVoid: { editable: false, type: "boolean" },
                                        RecurringPaymentType: { editable: false, type: "string" },
                                        DisplayOrder: { editable: true, type: "number" },
                                        IsActive: { editable: true, type: "boolean" }
                                    }
                                }
                            },
                            requestEnd: function (e) {
                                if (e.type == "update") {
                                    this.read();
                                }
                            },
                            error: function (e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            numeric: false,
                            previousNext: false,
                            info: false
                        },
                        editable: {
                            confirmation: false,
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [{
                            field: "FriendlyName",
                            title: "@T("Admin.Configuration.Payment.Methods.Fields.FriendlyName")",
                            width: 250
                        }, {
                            field: "SystemName",
                            title: "@T("Admin.Configuration.Payment.Methods.Fields.SystemName")",
                            width: 250
                        }, {
                            field: "LogoUrl",
                            title: "@T("Admin.Configuration.Payment.Methods.Fields.Logo")",
                            width: 100,
                            template: '<img src="#=LogoUrl#" />'
                        }, {
                            field: "SupportCapture",
                            title: "@T("Admin.Configuration.Payment.Methods.Fields.SupportCapture")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=SupportCapture#.gif" />'
                        }, {
                            field: "SupportRefund",
                            title: "@T("Admin.Configuration.Payment.Methods.Fields.SupportRefund")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=SupportRefund#.gif" />'
                        }, {
                            field: "SupportPartiallyRefund",
                            title: "@T("Admin.Configuration.Payment.Methods.Fields.SupportPartiallyRefund")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=SupportPartiallyRefund#.gif" />'
                        }, {
                            field: "SupportVoid",
                            title: "@T("Admin.Configuration.Payment.Methods.Fields.SupportVoid")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=SupportVoid#.gif" />'
                        }, {
                            field: "RecurringPaymentType",
                            title: "@T("Admin.Configuration.Payment.Methods.Fields.RecurringPaymentType")",
                            width: 250
                        }, {
                            field: "DisplayOrder",
                            title: "@T("Admin.Configuration.Payment.Methods.Fields.DisplayOrder")",
                            //integer format
                            format: "{0:0}",
                            width: 100
                        }, {
                            field: "IsActive",
                            title: "@T("Admin.Configuration.Payment.Methods.Fields.IsActive")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=IsActive#.gif" />'
                        }, {
                            field: "SystemName",
                            title: "@T("Admin.Configuration.Payment.Methods.Configure")",
                            width: 150,
                            template: '<a href="ConfigureMethod?systemName=#=SystemName#">@T("Admin.Configuration.Payment.Methods.Configure")</a>'
                        }, {
                            command: {name: "edit", text: "@T("Admin.Common.Edit")"},
                            title: "@T("Admin.Common.Edit")",
                            width: 150
                        }]
                    });
                });
            </script>
        </td>
    </tr>
</table>